### ISSUE TITLE
Upcoming WikibaseMediaInfo changes to StatementWidget class will break compatibility

### ISSUE THREAD

**Issue by egardner** [lucaswerkmeister/ACDC#3]
Hi Lucas–

I'm one of the developers on the Structured Data team at WMF. I wanted to let you know that a [recent patch we merged](https://github.com/wikimedia/mediawiki-extensions-WikibaseMediaInfo/commit/d69067b8da23dd8f0e98abc5694f38b59cb05e0f) makes a breaking change to the StatementWidget class, and a corresponding change in the code here is going to be needed to maintain compatibility.

We are in the process of introducing support for properties with datatypes beyond `wikibase-item`. String and Quantity type properties will require different UI elements to handle user input, etc. So the StatementWidget needs to know the property type in addition to the ID of its property when it is initialized. The previous `properties` map is no longer used. You can see the updated constructor here: https://github.com/wikimedia/mediawiki-extensions-WikibaseMediaInfo/blob/master/resources/statements/StatementWidget.js#L17-L18

I'm not very familiar with the workings of ACDC but I'm happy to help with a PR to correspond to our latest changes here. The main thing that will need to happen in addition to passing different arguments to the StatementWidget constructor is that the gadget will need to look up the property datatype of any properties being introduced. The simplest way to get this information is to make an API request (example [here](https://www.wikidata.org/wiki/Special:ApiSandbox#action=wbgetentities&format=json&ids=P180&props=datatype)) but there are other ways to get this data as well.

Happy to chat further about this. Thanks for your work on this tool!

**Comment by lucaswerkmeister** [comment]
Thanks a lot for the notice! If the breaking change is deployed to Beta, I should get notified anyways, I’ve got Travis CI set up to run browser tests against Beta each day. (I just fixed another incompatibility in #2, in fact.) I’ll try to look into this tomorrow.

> The main thing that will need to happen in addition to passing different arguments to the StatementWidget constructor is that the gadget will need to look up the property datatype of any properties being introduced. The simplest way to get this information is to make an API request (example here) but there are other ways to get this data as well.

Couldn’t the data type be included in the event sent by the `PropertyWidget`? I would assume that it already knows the data type from the property search it made, so it would be nice to avoid an extra API call here.

**Comment by lucaswerkmeister** [comment]
Oh, nevermind – the data type is already included, just in the second argument (I’d been looking for it in the first one) :)

**Comment by lucaswerkmeister** [comment]
Proposed fix is in #5.

**Comment by lucaswerkmeister** [comment]
(I see WIkibaseMediaInfo does essentially the same thing [here](https://github.com/wikimedia/mediawiki-extensions-WikibaseMediaInfo/commit/d69067b8da23dd8f0e98abc5694f38b59cb05e0f#diff-a0342732cb609174623de4df72aa1a6cR149), so let’s hope `data.datatype` isn’t just going to vanish at a moment’s notice.)

**Comment by egardner** [comment]
That's all correct – the AddPropertyWidget's `choose` event includes the `datatype` as a property of the `data` object in its payload. We only need to make a direct API request to get a property datatype in the case of pre-existing props which are present in the server-rendered page (as opposed to props added at runtime by the user).
